service: APIMirandaBackendFunction

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3

functions:
  app:
    handler: build/index.handler
    events:
      - http:
          path: /
          method: get
      
