service: MirandaBackendFunction

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3

functions:
  app:
    handler: build/index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: rooms
          method: get
      # Puedes agregar más rutas aquí
