service: APIMirandaBackendFunction

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3

functions:
  app:
    handler: build/index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /auth
          method: any
          cors:
            origin: '*'
            headers: 
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: "{myproxy+}"
          method: any
          cors:
            origin: '*'
            headers:
               - Content-Type
               - Authorization
            allowCredentials: true
