service: APIMirandaBackendFunction

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  stage: v1

functions:
  app:
    handler: build/index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: "{myproxy+}"
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
